### ISSUE TITLE
Plugin crash on plan

### ISSUE THREAD

**Issue by ndrone-kr** [harness/terraform-provider-harness#120]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- harness_secret_manager
- harness_application
- harness_encrypted_text
- harness_cloudprovider_azure

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
data "harness_secret_manager" "default" {
  default = true
}

data "harness_application" "posh_app" {
  name = "posh-azure-functionapp"
}

resource "harness_encrypted_text" "app_sp_secret" {
  name              = "functionapp_secret"
  value             = module.app_service_principal.password
  secret_manager_id = data.harness_secret_manager.default.id

  usage_scope {
    application_id = data.harness_application.posh_app.id
  }
}

data "azurerm_client_config" "current" {}

resource "harness_cloudprovider_azure" "functionapp" {
  name      = "functionapp"
  client_id = module.app_service_principal.service_principal_client_id
  tenant_id = data.azurerm_client_config.current.tenant_id
  key       = harness_encrypted_text.app_sp_secret.name
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
```
Error: Plugin did not respond

  with data.harness_secret_manager.default,
  on main.tf line 213, in data "harness_secret_manager" "default":
 213: data "harness_secret_manager" "default" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Error: Plugin did not respond

  with data.harness_application.posh_app,
  on main.tf line 217, in data "harness_application" "posh_app":
 217: data "harness_application" "posh_app" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-harness_v0.2.3 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcf8278]

goroutine 98 [running]:
github.com/harness/terraform-provider-harness/internal/service/cd/application.dataSourceApplicationRead({0x1106500, 0xc0005915c0}, 0x7f03d5982c98, {0xde0800, 0xc0001167b0})
	github.com/harness/terraform-provider-harness/internal/service/cd/application/application_data_source.go:71 +0x158
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00042d260, {0x1106500, 0xc0005915c0}, 0xd, {0xde0800, 0xc0001167b0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00042d260, {0x1106500, 0xc0005915c0}, 0xc0006c8e80, {0xde0800, 0xc0001167b0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00000d200, {0x1106458, 0xc0002a53c0}, 0xc0005bea00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1179 +0x[40](https://github.com/krogertechnology/MERCH-AZ-Admin/runs/6198693467?check_suite_focus=true#step:7:40)8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0000f0820, {0x1106500, 0xc000590e40}, 0xc0002fa5f0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:657 +0x45f
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xf46600, 0xc0000f0820}, {0x1106500, 0xc000590e40}, 0xc0005ce7e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000bc8c0, {0x111[41](https://github.com/krogertechnology/MERCH-AZ-Admin/runs/6198693467?check_suite_focus=true#step:7:41)00, 0xc0004ce340}, 0xc00030eea0, 0xc0004a8660, 0x16fa070, 0x0)
	google.golang.org/grpc@v1.[45](https://github.com/krogertechnology/MERCH-AZ-Admin/runs/6198693467?check_suite_focus=true#step:7:45).0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0000bc8c0, {0x1114100, 0xc0004ce340}, 0xc00030eea0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1[61](https://github.com/krogertechnology/MERCH-AZ-Admin/runs/6198693467?check_suite_focus=true#step:7:61)9 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-harness_v0.2.3 plugin crashed!
```

### Expected Behavior
What should have happened?
```
an output of the plan
```

### Actual Behavior
What actually happened?
```
the harness plugin crashed
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by micahlmartin** [comment]
Does this happen every time you run it?  Would you mind enabling debug logs with `export TF_LOG=DEBUG` and sending them to me at micah.martin@harness.io?

**Comment by ndrone-kr** [comment]
yes it happens everytime. I'm working on getting the logs together. I need to review the logs before sending.

**Comment by micahlmartin** [comment]
@ndrone-kr Can you try running just this and see what you get?

```
data "harness_secret_manager" "default" {
  default = true
}

output "secret_manager_id" {
  value = data.harness_secret_manager.default.id
}
```

**Comment by ndrone-kr** [comment]
@micahlmartin sad to say this was a setup issue. I forgot to place the harness API key as an environment variable in my workflow. Thank you for all the help.
