### ISSUE TITLE
harness_platform_connector_awscc terraform fails but successfully creates a connector

### ISSUE THREAD

**Issue by opp-svega** [harness/terraform-provider-harness#375]
### Terraform Version
```
❯ terraform --version
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/harness/harness v0.12.2
+ provider registry.terraform.io/hashicorp/aws v4.48.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Affected Resource(s)
- harness_platform_connector_aws

### Terraform Configuration Files
```hcl
resource "harness_platform_connector_awscc" "cloud_cost_connector" {
  identifier = replace("${var.environment}-cloud-cost-connector", "-", "_")
  name       = "${var.environment}-cloud-cost-connector"

  cross_account_access {
    role_arn    = aws_iam_role.harness_ce_role.arn
    external_id = "harness:${local.harness_aws_account_id}:${local.harness_account_id}"
  }
  features_enabled = ["VISIBILITY", "OPTIMIZATION"]
  account_id       = data.aws_caller_identity.current.account_id

  # From the master account
  report_name = "xxxxxxxx"
  s3_bucket   = "xxxxxxxx"

  tags = [for k, v in local.tags : "${k}:${v}"]
}
```
### Panic Output
```
2023-01-03T13:51:07.833-0600 [DEBUG] [aws-sdk-go] {}

Stack trace from the terraform-provider-harness_v0.12.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b2734c]

goroutine 13 [running]:
github.com/harness/terraform-provider-harness/internal/service/platform/connector.readConnectorAwsCC(0x205a908?, 0xc00043e000)
	github.com/harness/terraform-provider-harness/internal/service/platform/connector/aws_cc.go:165 +0x6c
github.com/harness/terraform-provider-harness/internal/service/platform/connector.resourceConnectorAwsCCRead({0x205a908?, 0xc00070c5a0?}, 0x0?, {0x1d30d00?, 0xc000628d40?})
	github.com/harness/terraform-provider-harness/internal/service/platform/connector/aws_cc.go:92 +0x66
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004defc0, {0x205a940, 0xc000804ab0}, 0xd?, {0x1d30d00, 0xc000628d40})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004defc0, {0x205a940, 0xc000804ab0}, 0xc0008605b0, {0x1d30d00, 0xc000628d40})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000e108, {0x205a940?, 0xc000804990?}, 0xc0000a4980)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000aa320, {0x205a940?, 0xc0008041b0?}, 0xc00070c2a0)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1e0e7a0?, 0xc0000aa320}, {0x205a940, 0xc0008041b0}, 0xc00030c070, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000021e0, {0x205d5e0, 0xc0001029c0}, 0xc0000e6000, 0xc00011c9c0, 0x26952d0, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000021e0, {0x205d5e0, 0xc0001029c0}, 0xc0000e6000, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-harness_v0.12.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2023-01-03T13:51:07.834-0600 [DEBUG] provider: plugin exited
ERRO[0008] 1 error occurred:
	* exit status 1
```

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform import harness_platform_connector_awscc.cloud_cost_connector sandbox1_account_cloud_cost_connector`

### Important Factoids
Both terraform apply and import are both failing with the same panic output.

**Comment by rssnyder** [comment]
@opp-svega this seems to be fixed in the latest release please try `0.23.0`
