### ISSUE TITLE
Error importing harness_platform_user

### ISSUE THREAD

**Issue by mmorejon** [harness/terraform-provider-harness#432]
### Terraform Version

```
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/harness/harness v0.14.3
```

### Affected Resource(s)

List of resources used:

- harness_platform_usergroup
- [harness_platform_user](https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_user#import)

### Terraform Configuration Files

```hcl
resource "harness_platform_user" "my_user" {
  emails      = ["my_private@email.com"]
  user_groups = ["my_team"]
  role_bindings {}
}
```

### Panic Output

```
Stack trace from the terraform-provider-harness_v0.14.3 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 55 [running]:
github.com/harness/terraform-provider-harness/helpers.glob..func5(0x14000560500, {0x140008d0b70?, 0x1013c534c?})
        github.com/harness/terraform-provider-harness/helpers/schema.go:207 +0x1c0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0x14000098240, {0x101868300, 0x140008d0b70}, 0x140005375b0, {0x140003b6000, 0x1a})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/provider.go:387 +0x14c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0x1400000c0a8, {0x101868300?, 0x140008d0a50?}, 0x140001481e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1088 +0xa8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0x1400039c320, {0x101868300?, 0x140008d0300?}, 0x140003020a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:848 +0x1a0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler({0x10180f7a0?, 0x1400039c320}, {0x101868300, 0x140008d0300}, 0x1400055c000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:403 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400046a000, {0x10186aee0, 0x14000583380}, 0x140008ce000, 0x14000522d50, 0x101e873b8, 0x0)
        google.golang.org/grpc@v1.52.3/server.go:1336 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x1400046a000, {0x10186aee0, 0x14000583380}, 0x140008ce000, 0x0)
        google.golang.org/grpc@v1.52.3/server.go:1704 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.52.3/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.52.3/server.go:963 +0x298

Error: The terraform-provider-harness_v0.14.3 plugin crashed!
```

### Expected Behavior

User imported through `harness_platform_user` resource.

### Actual Behavior

Plugin did not respond

### Steps to Reproduce

```
$ terraform import harness_platform_user.my_user my_private@email.com
```

**Comment by adiyaar24** [comment]
Hi @mmorejon 
Thanks for Reporting this to us , Things have been fixed 

Here is the updated way of doing this

> resource "harness_platform_user" "my_user" {
  email      =  "myprivate@email.com"
  user_groups = ["my_user"] }
  
  **Version -> 0.17.2**
  
  Note : We only support Terraform for Last 5 Version
  
  Do reach out to , if you encounter any other issues
  
  Thank you
