### ISSUE TITLE
Crash when using harness_platform_environment_group

### ISSUE THREAD

**Issue by janario** [harness/terraform-provider-harness#585]
We are using terraform to configure our NextGen environment, so far for most of the resources it went all good.

But when we set up a  `harness_platform_environment_group` after its apply, the next attempt starts to crash.

### Terraform Version
```
Terraform v1.5.0
on darwin_arm64
+ provider registry.terraform.io/harness/harness v0.22.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- harness_platform_environment_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "harness_platform_environment" "development_a" {
  identifier = "development_a"
  name       = "development_a"
  org_id     = "<org>"
  project_id = "" # IDEA gives warn as mandatory
  type       = "PreProduction"

  yaml       = <<-EOT
  environment:
    name: development_a
    identifier: development_a
    type: PreProduction
    orgIdentifier: <org>
    EOT
}
resource "harness_platform_environment" "development_b" {
  identifier = "development_b"
  name       = "development_b"
  org_id     = "<org>"
  project_id = "" # IDEA gives warn as mandatory
  type       = "PreProduction"

  yaml       = <<-EOT
  environment:
    name: development_b
    identifier: development_b
    type: PreProduction
    orgIdentifier: <org>
    EOT
}

resource "harness_platform_environment_group" "development" {
  identifier = "development_g"
  org_id     = "<org>"
  yaml       = <<-EOT
  environmentGroup:
    name: development_g
    identifier: development_g
    orgIdentifier: <org>
    envIdentifiers: [development_a, development_b]
    EOT
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

```
harness_platform_environment_group.development: Refreshing state... [id=development_g]
harness_platform_environment.development_a: Refreshing state... [id=development_a]
harness_platform_environment.development_b: Refreshing state... [id=development_b]
╷
│ Error: Plugin did not respond
│
│   with harness_platform_environment.development_a,
│   on environments.tf line 91, in resource "harness_platform_environment" "development_a":
│   91: resource "harness_platform_environment" "development_a" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with harness_platform_environment.development_b,
│   on environments.tf line 106, in resource "harness_platform_environment" "development_b":
│  106: resource "harness_platform_environment" "development_b" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with harness_platform_environment_group.development,
│   on environments.tf line 122, in resource "harness_platform_environment_group" "development":
│  122: resource "harness_platform_environment_group" "development" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-harness_v0.22.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1015c7a80]

goroutine 30 [running]:
github.com/harness/terraform-provider-harness/internal/service/platform/environment_group.resourceEnvironmentGroupRead({0x101b0af88?, 0x14000124780?}, 0x0?, {0x1019cc220?, 0x14000a169c0?})
	github.com/harness/terraform-provider-harness/internal/service/platform/environment_group/resource_environment_group.go:83 +0x210
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1400052ad20, {0x101b0afc0, 0x14000441e00}, 0xd?, {0x1019cc220, 0x14000a169c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:724 +0xec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400052ad20, {0x101b0afc0, 0x14000441e00}, 0x140003588f0, {0x1019cc220, 0x14000a169c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000198168, {0x101b0afc0?, 0x14000441ce0?}, 0x140006ec900)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x40c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140002f60a0, {0x101b0afc0?, 0x14000441320?}, 0x14000124480)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:748 +0x3ec
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x101ab1200?, 0x140002f60a0}, {0x101b0afc0, 0x14000441320}, 0x140002ec1c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:383 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000448000, {0x101b0df60, 0x14000003520}, 0x140000cbc20, 0x140002e5c50, 0x1021759b0, 0x0)
	google.golang.org/grpc@v1.55.0/server.go:1337 +0xc7c
google.golang.org/grpc.(*Server).handleStream(0x14000448000, {0x101b0df60, 0x14000003520}, 0x140000cbc20, 0x0)
	google.golang.org/grpc@v1.55.0/server.go:1714 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.55.0/server.go:959 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.55.0/server.go:957 +0x170

Error: The terraform-provider-harness_v0.22.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
What should have happened?

apply would be executed without issue

### Actual Behavior
What actually happened?

First apply is fine but it seems to corrupt the statefile and the next attempts crashes even before showing the plan

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by jagendra-mishra-phx** [comment]
This issue is also occurring for harness_platform_usergroup, harness_platform_roles and harness_platform_resource_group

Is there any fix available? Thanks

**Comment by jagendra-mishra-phx** [comment]
Thanks for the update. I did try with 0.24.4 for harness_platform_usergroup, harness_platform_roles and harness_platform_resource_group and it fails as my issue is with these resources. Thanks

**Comment by jagendra-mishra-phx** [comment]
Please ignore my issue as it was happening because I did use user value as null when creating userGroup. After removing that attribute it worked fine. Thanks.

**Comment by janario** [comment]
Tested with the latest version(0.28.2) and it seems fine now 

Thanks for the fix!
